// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package task

import (
	"tt.com/tt/internal/conf"
	"tt.com/tt/internal/data"
	"tt.com/tt/internal/data/daos"
	"tt.com/tt/internal/data/db"
	"tt.com/tt/internal/service"
)

// Injectors from wire.go:

func newService(config *conf.Config) (*service.Service, func(), error) {
	gormDB := db.NewDb(config)
	client, err := db.NewRedis(config)
	if err != nil {
		return nil, nil, err
	}
	dataSource := data.NewDataSource(config, gormDB, client)
	ttDao := daos.NewTtDao(dataSource)
	dao := &daos.Dao{
		Tt: ttDao,
	}
	ttService := service.NewTtService(dao)
	serviceService := &service.Service{
		Tt: ttService,
	}
	return serviceService, func() {
	}, nil
}
