// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"tt.com/tt/api"
	"tt.com/tt/api/app"
	"tt.com/tt/api/app/h5"
	"tt.com/tt/api/app/v1"
	"tt.com/tt/internal/conf"
	"tt.com/tt/internal/data"
	"tt.com/tt/internal/data/daos"
	"tt.com/tt/internal/data/db"
	"tt.com/tt/internal/services"
)

// Injectors from wire.go:

func NewApi(config *conf.Config) (*api.Api, func(), error) {
	gormDB := db.NewDb(config)
	client, err := db.NewRedis(config)
	if err != nil {
		return nil, nil, err
	}
	dataSource := data.NewDataSource(config, gormDB, client)
	ttDao := daos.NewTtDao(dataSource)
	dao := &daos.Dao{
		Tt: ttDao,
	}
	ttService := services.NewTtService(dao)
	service := &services.Service{
		Tt: ttService,
	}
	ttController := h5.NewTtController(service)
	h5H5 := &h5.H5{
		Tt: ttController,
	}
	v1TtController := v1.NewTtController(service)
	v1V1 := &v1.V1{
		Tt: v1TtController,
	}
	appApp := &app.App{
		H5: h5H5,
		V1: v1V1,
	}
	apiApi := &api.Api{
		App: appApp,
	}
	return apiApi, func() {
	}, nil
}
